//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Web.App_GlobalResources.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Web.App_GlobalResources.Reports.Reports", typeof(Reports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظف.
        /// </summary>
        public static string Asignee {
            get {
                return ResourceManager.GetString("Asignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكاوي حسب التصنيف.
        /// </summary>
        public static string CaseByCategory {
            get {
                return ResourceManager.GetString("CaseByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكاوي حسب الحالة.
        /// </summary>
        public static string CaseByState {
            get {
                return ResourceManager.GetString("CaseByState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير عدد الايام لكل شكوى  حتى اغلاقها.
        /// </summary>
        public static string CasesDaysByCategory {
            get {
                return ResourceManager.GetString("CasesDaysByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النسبة.
        /// </summary>
        public static string CasesPercent {
            get {
                return ResourceManager.GetString("CasesPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصنيف الحلات حسب الاهمية.
        /// </summary>
        public static string CasesPriorityByCategory {
            get {
                return ResourceManager.GetString("CasesPriorityByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقارير الشكاوي.
        /// </summary>
        public static string CasesReport {
            get {
                return ResourceManager.GetString("CasesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصنيف الحلات حسب الخطورة.
        /// </summary>
        public static string CasesSeverityByCategory {
            get {
                return ResourceManager.GetString("CasesSeverityByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLA Quality.
        /// </summary>
        public static string CasesSlaByCategory {
            get {
                return ResourceManager.GetString("CasesSlaByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد.
        /// </summary>
        public static string CassesCount {
            get {
                return ResourceManager.GetString("CassesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكاوي المغلقة.
        /// </summary>
        public static string ClosedCasesReport {
            get {
                return ResourceManager.GetString("ClosedCasesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الحالات المحلولة.
        /// </summary>
        public static string CountOfCases {
            get {
                return ResourceManager.GetString("CountOfCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكاوي المغلقة والمحلولة لكل اسبوع.
        /// </summary>
        public static string CreatedVsResolvedCasesPerWeek {
            get {
                return ResourceManager.GetString("CreatedVsResolvedCasesPerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص الايميل.
        /// </summary>
        public static string EmailDescription {
            get {
                return ResourceManager.GetString("EmailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة الحالات المحلولة.
        /// </summary>
        public static string PercentageOfResolvedCase {
            get {
                return ResourceManager.GetString("PercentageOfResolvedCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسوم البيانية.
        /// </summary>
        public static string ReportCharts {
            get {
                return ResourceManager.GetString("ReportCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ارساله الى.
        /// </summary>
        public static string SendTo {
            get {
                return ResourceManager.GetString("SendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤلف.
        /// </summary>
        public static string TxtCreatedBy {
            get {
                return ResourceManager.GetString("TxtCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الادخال.
        /// </summary>
        public static string TxtCreatedOn {
            get {
                return ResourceManager.GetString("TxtCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير عدد الحالات الغير محلولة لكل موظف.
        /// </summary>
        public static string UnresolvedCasesByUser {
            get {
                return ResourceManager.GetString("UnresolvedCasesByUser", resourceCulture);
            }
        }
    }
}
