//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Web.App_GlobalResources.Menu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Web.App_GlobalResources.Menu.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى باللغة العربية.
        /// </summary>
        public static string ArabicContent {
            get {
                return ResourceManager.GetString("ArabicContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اغلاق.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر.
        /// </summary>
        public static string ChooseParentMenu {
            get {
                return ResourceManager.GetString("ChooseParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى باللغة العبرية.
        /// </summary>
        public static string HebrewContent {
            get {
                return ResourceManager.GetString("HebrewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TxtActions {
            get {
                return ResourceManager.GetString("TxtActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة قسم.
        /// </summary>
        public static string TxtAddCategory {
            get {
                return ResourceManager.GetString("TxtAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة عنصر جديد.
        /// </summary>
        public static string TxtAddNewMenu {
            get {
                return ResourceManager.GetString("TxtAddNewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤلف.
        /// </summary>
        public static string TxtCreatedBy {
            get {
                return ResourceManager.GetString("TxtCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الادخال.
        /// </summary>
        public static string TxtCreatedOn {
            get {
                return ResourceManager.GetString("TxtCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد انك تريد حذف هذا العنصر.
        /// </summary>
        public static string TxtDeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("TxtDeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string TxtDescription {
            get {
                return ResourceManager.GetString("TxtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايقونة.
        /// </summary>
        public static string TxtIcon {
            get {
                return ResourceManager.GetString("TxtIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارفق صورة.
        /// </summary>
        public static string TxtMainImageUrl {
            get {
                return ResourceManager.GetString("TxtMainImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة.
        /// </summary>
        public static string TxtPageId {
            get {
                return ResourceManager.GetString("TxtPageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط الصفحة.
        /// </summary>
        public static string TxtPageUrl {
            get {
                return ResourceManager.GetString("TxtPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة.
        /// </summary>
        public static string TxtParentId {
            get {
                return ResourceManager.GetString("TxtParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترتيب.
        /// </summary>
        public static string TxtSortOrder {
            get {
                return ResourceManager.GetString("TxtSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string TxtStatus {
            get {
                return ResourceManager.GetString("TxtStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string TxtTitle {
            get {
                return ResourceManager.GetString("TxtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من دون ايقونة.
        /// </summary>
        public static string TxtUnKnownIcon {
            get {
                return ResourceManager.GetString("TxtUnKnownIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل عنصر القائمة.
        /// </summary>
        public static string TxtUpdateMenu {
            get {
                return ResourceManager.GetString("TxtUpdateMenu", resourceCulture);
            }
        }
    }
}
