//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Web.App_GlobalResources.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Web.App_GlobalResources.General.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث متقدم.
        /// </summary>
        public static string AdvanceSearch {
            get {
                return ResourceManager.GetString("AdvanceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى باللغة العربية.
        /// </summary>
        public static string ArabicContent {
            get {
                return ResourceManager.GetString("ArabicContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحريك للاسفل.
        /// </summary>
        public static string BtnMoveDown {
            get {
                return ResourceManager.GetString("BtnMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحريك لليسار.
        /// </summary>
        public static string BtnMoveLeft {
            get {
                return ResourceManager.GetString("BtnMoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحريك لليمين.
        /// </summary>
        public static string BtnMoveRight {
            get {
                return ResourceManager.GetString("BtnMoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحريك للاعلى.
        /// </summary>
        public static string BtnMoveUp {
            get {
                return ResourceManager.GetString("BtnMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string btnNewsLetterSend {
            get {
                return ResourceManager.GetString("btnNewsLetterSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اغلاق.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الشكوى.
        /// </summary>
        public static string ComplaintNo {
            get {
                return ResourceManager.GetString("ComplaintNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت المعالجة من.
        /// </summary>
        public static string ElapseTimeFrom {
            get {
                return ResourceManager.GetString("ElapseTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت المعالجة الى.
        /// </summary>
        public static string ElapseTimeTo {
            get {
                return ResourceManager.GetString("ElapseTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايميلات.
        /// </summary>
        public static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل جميع المعلومات.
        /// </summary>
        public static string ExportAllFields {
            get {
                return ResourceManager.GetString("ExportAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ من.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت من.
        /// </summary>
        public static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى باللغة العبرية.
        /// </summary>
        public static string HebrewContent {
            get {
                return ResourceManager.GetString("HebrewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string LinkDetails {
            get {
                return ResourceManager.GetString("LinkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الصفحة الرئيسية.
        /// </summary>
        public static string LinkEditHomePage {
            get {
                return ResourceManager.GetString("LinkEditHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إقرأ المزيد.
        /// </summary>
        public static string LinkReadMoreNews {
            get {
                return ResourceManager.GetString("LinkReadMoreNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء اضافة ايميل..
        /// </summary>
        public static string PleaseAddEmails {
            get {
                return ResourceManager.GetString("PleaseAddEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى كتابة عناوين البريد الالكتروني مفصولة بفاصلة ,.
        /// </summary>
        public static string PleaseWriteEmailsSeparatedWithComma {
            get {
                return ResourceManager.GetString("PleaseWriteEmailsSeparatedWithComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال التقرير عن طريق الايميل.
        /// </summary>
        public static string SendReportAsEmail {
            get {
                return ResourceManager.GetString("SendReportAsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الارسال بنجاح.
        /// </summary>
        public static string SentSuccessfully {
            get {
                return ResourceManager.GetString("SentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ الى.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت الى.
        /// </summary>
        public static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احداث ومناسبات قريبة قادمة.
        /// </summary>
        public static string TxtCommingEvents {
            get {
                return ResourceManager.GetString("TxtCommingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string TxtDescription {
            get {
                return ResourceManager.GetString("TxtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارفق صورة.
        /// </summary>
        public static string TxtMainImageUrl {
            get {
                return ResourceManager.GetString("TxtMainImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الصفحة الرئيسية.
        /// </summary>
        public static string TxtMangeHomePage {
            get {
                return ResourceManager.GetString("TxtMangeHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاهد المزيد.
        /// </summary>
        public static string TxtSeeMore {
            get {
                return ResourceManager.GetString("TxtSeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        public static string TxtShow {
            get {
                return ResourceManager.GetString("TxtShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض اشترك بالقائمة البريدية .
        /// </summary>
        public static string TxtShowEmail {
            get {
                return ResourceManager.GetString("TxtShowEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الاحداث والمناسبات القريبة .
        /// </summary>
        public static string TxtShowEvents {
            get {
                return ResourceManager.GetString("TxtShowEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الاسئله الشائعه.
        /// </summary>
        public static string TxtShowFaq {
            get {
                return ResourceManager.GetString("TxtShowFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض شريط في الموقع .
        /// </summary>
        public static string TxtShowMarquee {
            get {
                return ResourceManager.GetString("TxtShowMarquee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض السلايدر.
        /// </summary>
        public static string TxtShowSlider {
            get {
                return ResourceManager.GetString("TxtShowSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال النص مرفقا بالصورة.
        /// </summary>
        public static string TxtSliderUploadImages {
            get {
                return ResourceManager.GetString("TxtSliderUploadImages", resourceCulture);
            }
        }
        public static string Name
        {
            get{  return ResourceManager.GetString("Name", resourceCulture); }
        }
        public static string Email
        {
            get { return ResourceManager.GetString("Email", resourceCulture); }
        }
        public static string Address
        {
            get { return ResourceManager.GetString("Address", resourceCulture); }
        }
        public static string Mobile
        {
            get { return ResourceManager.GetString("Mobile", resourceCulture); }
        }
        public static string Notes
        {
            get { return ResourceManager.GetString("Notes", resourceCulture); }
        }
        public static string Status
        {
            get { return ResourceManager.GetString("Status", resourceCulture); }
        }
        public static string CreatedDate
        {
            get { return ResourceManager.GetString("CreatedDate", resourceCulture); }
        }
        public static string ActivityDate
        {
            get { return ResourceManager.GetString("ActivityDate", resourceCulture); }
        }
        public static string ActivityStatus
        {
            get { return ResourceManager.GetString("ActivityStatus", resourceCulture); }
        }
        public static string ActivityType
        {
            get { return ResourceManager.GetString("ActivityType", resourceCulture); }
        }
        public static string AddActivity
        {
            get { return ResourceManager.GetString("AddActivity", resourceCulture); }
        }
        public static string ActivityDetails
        {
            get { return ResourceManager.GetString("ActivityDetails", resourceCulture); }
        }
        public static string AssigneeUser
        {
            get { return ResourceManager.GetString("AssigneeUser", resourceCulture); }
        }
    }
}
