//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Web.App_GlobalResources.SystemCases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Web.App_GlobalResources.SystemCases.SystemCases", typeof(SystemCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعّال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مرفق للتعليق.
        /// </summary>
        public static string AddAttachmentToTheComment {
            get {
                return ResourceManager.GetString("AddAttachmentToTheComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المقدم.
        /// </summary>
        public static string ApplicantName {
            get {
                return ResourceManager.GetString("ApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد المتقدمين.
        /// </summary>
        public static string ApplicantsCount {
            get {
                return ResourceManager.GetString("ApplicantsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى باللغة العربية.
        /// </summary>
        public static string ArabicContent {
            get {
                return ResourceManager.GetString("ArabicContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مؤرشف.
        /// </summary>
        public static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظف المسئول.
        /// </summary>
        public static string AssigneeUserName {
            get {
                return ResourceManager.GetString("AssigneeUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اغلاق.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string BtnDetails {
            get {
                return ResourceManager.GetString("BtnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المواطن.
        /// </summary>
        public static string Citizen {
            get {
                return ResourceManager.GetString("Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المواطن, رقم الهوية, رقم الهاتف.
        /// </summary>
        public static string CitizenSearch {
            get {
                return ResourceManager.GetString("CitizenSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الاغلاق.
        /// </summary>
        public static string CloseDate {
            get {
                return ResourceManager.GetString("CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليق.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الشكوى.
        /// </summary>
        public static string ComplaintId {
            get {
                return ResourceManager.GetString("ComplaintId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الشكوى.
        /// </summary>
        public static string ComplaintTitle {
            get {
                return ResourceManager.GetString("ComplaintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الايام.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الحالة.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحالة.
        /// </summary>
        public static string EmergencyId {
            get {
                return ResourceManager.GetString("EmergencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحالة.
        /// </summary>
        public static string EmergencyTitle {
            get {
                return ResourceManager.GetString("EmergencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية من.
        /// </summary>
        public static string EndDateFrom {
            get {
                return ResourceManager.GetString("EndDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية الى.
        /// </summary>
        public static string EndDateTo {
            get {
                return ResourceManager.GetString("EndDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من تاريخ.
        /// </summary>
        public static string FormDate {
            get {
                return ResourceManager.GetString("FormDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم النموذج.
        /// </summary>
        public static string FormId {
            get {
                return ResourceManager.GetString("FormId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم النموذج.
        /// </summary>
        public static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى باللغة العبرية.
        /// </summary>
        public static string HebrewContent {
            get {
                return ResourceManager.GetString("HebrewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الوظيفة.
        /// </summary>
        public static string JobId {
            get {
                return ResourceManager.GetString("JobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الوظيفة.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر المناقصات المقدمة.
        /// </summary>
        public static string LastTendersSubmitted {
            get {
                return ResourceManager.GetString("LastTendersSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع (الاحداثيات).
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التقديم.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطلب.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المواطن.
        /// </summary>
        public static string PersonInformation {
            get {
                return ResourceManager.GetString("PersonInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاهمية.
        /// </summary>
        public static string PriorityName {
            get {
                return ResourceManager.GetString("PriorityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية من.
        /// </summary>
        public static string PublishDateFrom {
            get {
                return ResourceManager.GetString("PublishDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية الى.
        /// </summary>
        public static string PublishDateTo {
            get {
                return ResourceManager.GetString("PublishDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطورة.
        /// </summary>
        public static string SeverityName {
            get {
                return ResourceManager.GetString("SeverityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضهار التعليق للمواطن.
        /// </summary>
        public static string ShowCommentToTheCitizen {
            get {
                return ResourceManager.GetString("ShowCommentToTheCitizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علامات.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المناقصة.
        /// </summary>
        public static string TenderId {
            get {
                return ResourceManager.GetString("TenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المناقصة.
        /// </summary>
        public static string TenderTitle {
            get {
                return ResourceManager.GetString("TenderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الى تاريخ.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TxtActions {
            get {
                return ResourceManager.GetString("TxtActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة شكوى.
        /// </summary>
        public static string TxtAddCase {
            get {
                return ResourceManager.GetString("TxtAddCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        public static string TxtAddNewCase {
            get {
                return ResourceManager.GetString("TxtAddNewCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤلف.
        /// </summary>
        public static string TxtCreatedBy {
            get {
                return ResourceManager.GetString("TxtCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الادخال.
        /// </summary>
        public static string TxtCreatedOn {
            get {
                return ResourceManager.GetString("TxtCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد انك تريد حذف هذا العنصر.
        /// </summary>
        public static string TxtDeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("TxtDeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string TxtDescription {
            get {
                return ResourceManager.GetString("TxtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string TxtStatus {
            get {
                return ResourceManager.GetString("TxtStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الطلب.
        /// </summary>
        public static string TxtUpdateCase {
            get {
                return ResourceManager.GetString("TxtUpdateCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string TxtUploadFile {
            get {
                return ResourceManager.GetString("TxtUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الشكوى.
        /// </summary>
        public static string TypeId {
            get {
                return ResourceManager.GetString("TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطلب.
        /// </summary>
        public static string UniqueId {
            get {
                return ResourceManager.GetString("UniqueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفائز.
        /// </summary>
        public static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
    }
}
