//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Web.App_GlobalResources.Sla {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sla {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sla() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Web.App_GlobalResources.Sla.Sla", typeof(Sla).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى باللغة العربية.
        /// </summary>
        public static string ArabicContent {
            get {
                return ResourceManager.GetString("ArabicContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اغلاق.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cc Assignee.
        /// </summary>
        public static string CcAssignee {
            get {
                return ResourceManager.GetString("CcAssignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى باللغة العبرية.
        /// </summary>
        public static string HebrewContent {
            get {
                return ResourceManager.GetString("HebrewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الساعات للحالة.
        /// </summary>
        public static string HoursPerState {
            get {
                return ResourceManager.GetString("HoursPerState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالات المستثنية.
        /// </summary>
        public static string IgnoredStates {
            get {
                return ResourceManager.GetString("IgnoredStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مع الاجازات.
        /// </summary>
        public static string IncludingHolidays {
            get {
                return ResourceManager.GetString("IncludingHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الاشعارات.
        /// </summary>
        public static string NotificationCount {
            get {
                return ResourceManager.GetString("NotificationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشعار قبل (بالدقائق).
        /// </summary>
        public static string NotifyBefore {
            get {
                return ResourceManager.GetString("NotifyBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال للمدير.
        /// </summary>
        public static string PropogateToManager {
            get {
                return ResourceManager.GetString("PropogateToManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئات.
        /// </summary>
        public static string SlaCategories {
            get {
                return ResourceManager.GetString("SlaCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستوى الخدمة.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TxtActions {
            get {
                return ResourceManager.GetString("TxtActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة جديد.
        /// </summary>
        public static string TxtAddNewSla {
            get {
                return ResourceManager.GetString("TxtAddNewSla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد انك تريد حذف هذا العنصر.
        /// </summary>
        public static string TxtDeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("TxtDeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرسال الى المواطن.
        /// </summary>
        public static string TxtSendToCitizen {
            get {
                return ResourceManager.GetString("TxtSendToCitizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرسل الى الموظف.
        /// </summary>
        public static string TxtSendToEmployee {
            get {
                return ResourceManager.GetString("TxtSendToEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string TxtStatus {
            get {
                return ResourceManager.GetString("TxtStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string TxtUpdateSla {
            get {
                return ResourceManager.GetString("TxtUpdateSla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايام العمل.
        /// </summary>
        public static string WorkingDaysIncludingHolidays {
            get {
                return ResourceManager.GetString("WorkingDaysIncludingHolidays", resourceCulture);
            }
        }
    }
}
