//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DataEntity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrmSystemEntities : DbContext
    {
        public CrmSystemEntities()
            : base("name=CrmSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<CasesByEmail> CasesByEmails { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryTranslation> CategoryTranslations { get; set; }
        public virtual DbSet<CommunicationLog> CommunicationLogs { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DepartmentTranslation> DepartmentTranslations { get; set; }
        public virtual DbSet<DetailsLookup> DetailsLookups { get; set; }
        public virtual DbSet<DetailsLookupTranslation> DetailsLookupTranslations { get; set; }
        public virtual DbSet<Lead_Activity> Lead_Activity { get; set; }
        public virtual DbSet<Lead> Leads { get; set; }
        public virtual DbSet<MasterLookup> MasterLookups { get; set; }
        public virtual DbSet<MasterLookupTranslation> MasterLookupTranslations { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuTranslation> MenuTranslations { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<SMSTemplate> SMSTemplates { get; set; }
        public virtual DbSet<SMSTemplateTranslation> SMSTemplateTranslations { get; set; }
        public virtual DbSet<StateHistory> StateHistories { get; set; }
        public virtual DbSet<StateTransitionsConfiguration> StateTransitionsConfigurations { get; set; }
        public virtual DbSet<SysCaseComment> SysCaseComments { get; set; }
        public virtual DbSet<SystemCaseAttachment> SystemCaseAttachments { get; set; }
        public virtual DbSet<SystemCas> SystemCases { get; set; }
        public virtual DbSet<SystemFile> SystemFiles { get; set; }
        public virtual DbSet<SystemFileTranslation> SystemFileTranslations { get; set; }
        public virtual DbSet<SystemLog> SystemLogs { get; set; }
        public virtual DbSet<SystemSetting> SystemSettings { get; set; }
        public virtual DbSet<SystemSettingTranslation> SystemSettingTranslations { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserProfileHoliday> UserProfileHolidays { get; set; }
        public virtual DbSet<UserProfileOffDay> UserProfileOffDays { get; set; }
        public virtual DbSet<UserProfileTranslation> UserProfileTranslations { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
    }
}
