//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DataEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsLookupTranslation
    {
        public int Id { get; set; }
        public int DetailsLookupId { get; set; }
        public string Value { get; set; }
        public int LanguageId { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual DetailsLookup DetailsLookup { get; set; }
    }
}
