//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DataEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuTranslation
    {
        public int Id { get; set; }
        public int MenuId { get; set; }
        public int LanguageId { get; set; }
        public bool IsDefault { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
