//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DataEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateTransitionsConfiguration
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int StateFrom { get; set; }
        public int StateTo { get; set; }
        public Nullable<int> AssigneeId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public int CategoryType { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
