//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DataEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemCas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemCas()
        {
            this.StateHistories = new HashSet<StateHistory>();
            this.SysCaseComments = new HashSet<SysCaseComment>();
            this.SystemCaseAttachments = new HashSet<SystemCaseAttachment>();
        }
    
        public int Id { get; set; }
        public System.Guid UniqueId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SeverityId { get; set; }
        public Nullable<int> SeverityValue { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> PriorityValue { get; set; }
        public string Title { get; set; }
        public string Tags { get; set; }
        public Nullable<int> AssigneeId { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string Address { get; set; }
        public string Location { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string FormId { get; set; }
        public string FormName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateHistory> StateHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysCaseComment> SysCaseComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemCaseAttachment> SystemCaseAttachments { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
