//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DataEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemCaseAttachment
    {
        public int Id { get; set; }
        public int FileId { get; set; }
        public int CaseId { get; set; }
    
        public virtual SystemCas SystemCas { get; set; }
        public virtual SystemFile SystemFile { get; set; }
    }
}
