//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Core.App_GlobalResources.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Core.App_GlobalResources.General.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسود و ابيض.
        /// </summary>
        public static string AccessibilityBlackWhite {
            get {
                return ResourceManager.GetString("AccessibilityBlackWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تباين.
        /// </summary>
        public static string AccessibilityContrast {
            get {
                return ResourceManager.GetString("AccessibilityContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + تكبير.
        /// </summary>
        public static string AccessibilityMaximize {
            get {
                return ResourceManager.GetString("AccessibilityMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - تصغير.
        /// </summary>
        public static string AccessibilityMinimize {
            get {
                return ResourceManager.GetString("AccessibilityMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحجم الاصلي.
        /// </summary>
        public static string AccessibilityOriginalSize {
            get {
                return ResourceManager.GetString("AccessibilityOriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقالات.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string BtnExcel {
            get {
                return ResourceManager.GetString("BtnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكاوي حسب التصنيف.
        /// </summary>
        public static string CaseByCategoryReport {
            get {
                return ResourceManager.GetString("CaseByCategoryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكاوي حسب الحالة.
        /// </summary>
        public static string CaseByStateReport {
            get {
                return ResourceManager.GetString("CaseByStateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير عدد الايام لكل شكوى  حتى اغلاقها.
        /// </summary>
        public static string CasesDaysByCategoryReport {
            get {
                return ResourceManager.GetString("CasesDaysByCategoryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصنيف الحلات حسب الاهمية.
        /// </summary>
        public static string CasesPriorityByCategoryReport {
            get {
                return ResourceManager.GetString("CasesPriorityByCategoryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقارير الشكاوي.
        /// </summary>
        public static string CasesReport {
            get {
                return ResourceManager.GetString("CasesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالات المرسلة بالايميل.
        /// </summary>
        public static string CasesSentByEmail {
            get {
                return ResourceManager.GetString("CasesSentByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصنيف الحلات حسب الخطورة.
        /// </summary>
        public static string CasesSeverityByCategoryReport {
            get {
                return ResourceManager.GetString("CasesSeverityByCategoryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستوى الخدمة.
        /// </summary>
        public static string CasesSlaByCategory {
            get {
                return ResourceManager.GetString("CasesSlaByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئات.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكاوي المغلقة.
        /// </summary>
        public static string ClosedCasesReport {
            get {
                return ResourceManager.GetString("ClosedCasesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكاوي.
        /// </summary>
        public static string Complaints {
            get {
                return ResourceManager.GetString("Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكاوي المغلقة والمحلولة لكل اسبوع.
        /// </summary>
        public static string CreatedVsResolvedCasesPerWeekReport {
            get {
                return ResourceManager.GetString("CreatedVsResolvedCasesPerWeekReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطوارئ.
        /// </summary>
        public static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النماذج.
        /// </summary>
        public static string Froms {
            get {
                return ResourceManager.GetString("Froms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الذهاب للرئيسية.
        /// </summary>
        public static string GoToHome {
            get {
                return ResourceManager.GetString("GoToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظائف.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاركة المعرفة.
        /// </summary>
        public static string KnowledgeShare {
            get {
                return ResourceManager.GetString("KnowledgeShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة الملفات.
        /// </summary>
        public static string LinkArchiving {
            get {
                return ResourceManager.GetString("LinkArchiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاقسام.
        /// </summary>
        public static string LinkCategories {
            get {
                return ResourceManager.GetString("LinkCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة محتوى الموقع.
        /// </summary>
        public static string LinkCms {
            get {
                return ResourceManager.GetString("LinkCms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكاوي.
        /// </summary>
        public static string LinkComplaints {
            get {
                return ResourceManager.GetString("LinkComplaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        public static string LinkContact {
            get {
                return ResourceManager.GetString("LinkContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        public static string LinkControlPanel {
            get {
                return ResourceManager.GetString("LinkControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدوائر.
        /// </summary>
        public static string LinkDepartment {
            get {
                return ResourceManager.GetString("LinkDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطوارئ.
        /// </summary>
        public static string LinkEmergency {
            get {
                return ResourceManager.GetString("LinkEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاحداث والمناسبات.
        /// </summary>
        public static string LinkEvents {
            get {
                return ResourceManager.GetString("LinkEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع الاسئلة.
        /// </summary>
        public static string LinkFormQuestionTypes {
            get {
                return ResourceManager.GetString("LinkFormQuestionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النماذج.
        /// </summary>
        public static string LinkForms {
            get {
                return ResourceManager.GetString("LinkForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرض الصور.
        /// </summary>
        public static string LinkGallery {
            get {
                return ResourceManager.GetString("LinkGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string LinkHome {
            get {
                return ResourceManager.GetString("LinkHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وظائف.
        /// </summary>
        public static string LinkJobs {
            get {
                return ResourceManager.GetString("LinkJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string LinkLogin {
            get {
                return ResourceManager.GetString("LinkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string LinkLogOff {
            get {
                return ResourceManager.GetString("LinkLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعريفات.
        /// </summary>
        public static string LinkLookup {
            get {
                return ResourceManager.GetString("LinkLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكاوي.
        /// </summary>
        public static string LinkManageCase {
            get {
                return ResourceManager.GetString("LinkManageCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الصفحه الرئيسية.
        /// </summary>
        public static string LinkManageHome {
            get {
                return ResourceManager.GetString("LinkManageHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة.
        /// </summary>
        public static string LinkMenu {
            get {
                return ResourceManager.GetString("LinkMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحات.
        /// </summary>
        public static string LinkPages {
            get {
                return ResourceManager.GetString("LinkPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات.
        /// </summary>
        public static string LinkPermission {
            get {
                return ResourceManager.GetString("LinkPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلاحيات الوظيفة.
        /// </summary>
        public static string LinkRolePermissions {
            get {
                return ResourceManager.GetString("LinkRolePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        public static string LinkServices {
            get {
                return ResourceManager.GetString("LinkServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستوى الخدمة.
        /// </summary>
        public static string LinkSla {
            get {
                return ResourceManager.GetString("LinkSla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلايدر.
        /// </summary>
        public static string LinkSlider {
            get {
                return ResourceManager.GetString("LinkSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل الحركات.
        /// </summary>
        public static string LinkStateHistory {
            get {
                return ResourceManager.GetString("LinkStateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات تغيير الحالة.
        /// </summary>
        public static string LinkStateTransitionsConfigration {
            get {
                return ResourceManager.GetString("LinkStateTransitionsConfigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانات الصفحة الشخصية.
        /// </summary>
        public static string LinkUserProfileFields {
            get {
                return ResourceManager.GetString("LinkUserProfileFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string LinkUsers {
            get {
                return ResourceManager.GetString("LinkUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة الحالات المحلولة.
        /// </summary>
        public static string PercentageOfResolvedCase {
            get {
                return ResourceManager.GetString("PercentageOfResolvedCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الشخصي.
        /// </summary>
        public static string PersonalAccount {
            get {
                return ResourceManager.GetString("PersonalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المواطن.
        /// </summary>
        public static string PersonInformation {
            get {
                return ResourceManager.GetString("PersonInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسوم البيانية.
        /// </summary>
        public static string ReportCharts {
            get {
                return ResourceManager.GetString("ReportCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقارير.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماذج الرسائل.
        /// </summary>
        public static string SMSTemplates {
            get {
                return ResourceManager.GetString("SMSTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعدادات النظام.
        /// </summary>
        public static string SystemSetting {
            get {
                return ResourceManager.GetString("SystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المناقصات.
        /// </summary>
        public static string Tenders {
            get {
                return ResourceManager.GetString("Tenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه التواصل بنا .
        /// </summary>
        public static string TxtContactUs {
            get {
                return ResourceManager.GetString("TxtContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطوارئ.
        /// </summary>
        public static string TxtEmergency {
            get {
                return ResourceManager.GetString("TxtEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسئلة شائعه.
        /// </summary>
        public static string TxtFaqs {
            get {
                return ResourceManager.GetString("TxtFaqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتقدمين للوظائف.
        /// </summary>
        public static string TxtJobs {
            get {
                return ResourceManager.GetString("TxtJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري رفع الصورة/ملف.
        /// </summary>
        public static string TxtLoaderImage {
            get {
                return ResourceManager.GetString("TxtLoaderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string TxtManage {
            get {
                return ResourceManager.GetString("TxtManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الطلب.
        /// </summary>
        public static string TxtNameOfTheRequest {
            get {
                return ResourceManager.GetString("TxtNameOfTheRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النشرة البريدية.
        /// </summary>
        public static string TxtNewsLetter {
            get {
                return ResourceManager.GetString("TxtNewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من.
        /// </summary>
        public static string TxtPaginationFrom {
            get {
                return ResourceManager.GetString("TxtPaginationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد العناصر.
        /// </summary>
        public static string TxtPaginationItemNo {
            get {
                return ResourceManager.GetString("TxtPaginationItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحة.
        /// </summary>
        public static string TxtPaginationPage {
            get {
                return ResourceManager.GetString("TxtPaginationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string TxtSearch {
            get {
                return ResourceManager.GetString("TxtSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث عن ....
        /// </summary>
        public static string TxtSearchFor {
            get {
                return ResourceManager.GetString("TxtSearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSM IT Solutions.
        /// </summary>
        public static string TxtSmsm {
            get {
                return ResourceManager.GetString("TxtSmsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقديم الطلب.
        /// </summary>
        public static string TxtSubmissionOfTheApplication {
            get {
                return ResourceManager.GetString("TxtSubmissionOfTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعدادات الموقع.
        /// </summary>
        public static string TxtSystemSetting {
            get {
                return ResourceManager.GetString("TxtSystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا.
        /// </summary>
        public static string TxtWelcome {
            get {
                return ResourceManager.GetString("TxtWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام الشكاوي.
        /// </summary>
        public static string WebsiteName {
            get {
                return ResourceManager.GetString("WebsiteName", resourceCulture);
            }
        }
    }
}
