//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Web.App_GlobalResources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Register {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Register() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Web.App_GlobalResources.Account.Register", typeof(Register).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل.
        /// </summary>
        public static string BtnRegister {
            get {
                return ResourceManager.GetString("BtnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور.
        /// </summary>
        public static string ForgetPasswordLink {
            get {
                return ResourceManager.GetString("ForgetPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد و كلمه المرور.
        /// </summary>
        public static string LblEmailAndPassword {
            get {
                return ResourceManager.GetString("LblEmailAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات عامة.
        /// </summary>
        public static string LblInformation {
            get {
                return ResourceManager.GetString("LblInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        public static string LoginLink {
            get {
                return ResourceManager.GetString("LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الشخصية.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل في الموقع.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string TxtAddress {
            get {
                return ResourceManager.GetString("TxtAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string TxtBirthDay {
            get {
                return ResourceManager.GetString("TxtBirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البلدة.
        /// </summary>
        public static string TxtCityId {
            get {
                return ResourceManager.GetString("TxtCityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string TxtConfirmPassword {
            get {
                return ResourceManager.GetString("TxtConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string TxtEmail {
            get {
                return ResourceManager.GetString("TxtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاكس.
        /// </summary>
        public static string TxtFax {
            get {
                return ResourceManager.GetString("TxtFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل.
        /// </summary>
        public static string TxtFullName {
            get {
                return ResourceManager.GetString("TxtFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string TxtGenderLookupId {
            get {
                return ResourceManager.GetString("TxtGenderLookupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية.
        /// </summary>
        public static string TxtIdNumber {
            get {
                return ResourceManager.GetString("TxtIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر ظهور.
        /// </summary>
        public static string TxtLastLogin {
            get {
                return ResourceManager.GetString("TxtLastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة الاجتماعية.
        /// </summary>
        public static string TxtMartialStatusLookupId {
            get {
                return ResourceManager.GetString("TxtMartialStatusLookupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف الخلوي.
        /// </summary>
        public static string TxtMobile {
            get {
                return ResourceManager.GetString("TxtMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string TxtPassword {
            get {
                return ResourceManager.GetString("TxtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string TxtPhoneNumber {
            get {
                return ResourceManager.GetString("TxtPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلومات الشخصية.
        /// </summary>
        public static string TxtProfileInfo {
            get {
                return ResourceManager.GetString("TxtProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة الشخصية.
        /// </summary>
        public static string TxtProfilePath {
            get {
                return ResourceManager.GetString("TxtProfilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة.
        /// </summary>
        public static string TxtProvinceId {
            get {
                return ResourceManager.GetString("TxtProvinceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التجمع.
        /// </summary>
        public static string TxtRegionId {
            get {
                return ResourceManager.GetString("TxtRegionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string TxtStatus {
            get {
                return ResourceManager.GetString("TxtStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاستمارات المقدمة.
        /// </summary>
        public static string TxtUserForms {
            get {
                return ResourceManager.GetString("TxtUserForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string TxtUsername {
            get {
                return ResourceManager.GetString("TxtUsername", resourceCulture);
            }
        }
    }
}
